#!/usr/bin/env bash
# Requirement tooling, sourced by run.sh. Needs $RESULTS (test output) for status.
STORY=story/STORY.md

# Prints "ID|status|title" per requirement.
req_list() {
  grep -E '^### R-[0-9]{3} \[(planned|active|done)\]' "$STORY" |
    sed -E 's/^### (R-[0-9]{3}) \[([a-z]+)\] (.*)$/\1|\2|\3/'
}

req_test_files() { ls tests/story/test_r"${1#R-}"_*.gd 2>/dev/null; }

# reqs: fail if an active/done requirement has no test file.
cmd_reqs() {
  [ -f "$STORY" ] || { echo "reqs: $STORY not found" >&2; return 1; }
  local missing=0 total=0 id st title
  while IFS='|' read -r id st title; do
    total=$((total + 1))
    if [ "$st" != planned ] && [ -z "$(req_test_files "$id")" ]; then
      echo "MISSING TEST  $id [$st] $title  (expected tests/story/test_r${id#R-}_*.gd)" >&2
      missing=$((missing + 1))
    fi
  done < <(req_list)
  [ "$total" -eq 0 ] && { echo "reqs: no requirements found in $STORY" >&2; return 1; }
  echo "reqs: $total requirements, $missing missing tests"
  [ "$missing" -eq 0 ]
}

# story: run all tests, regenerate story/progress.md, fail on missing/failing.
cmd_story() {
  local results rc=0 bad=0 id st title files res icon
  results="$(cmd_test 2>&1)" || rc=$?
  echo "$results" | tail -n 40
  {
    echo "# Story progress"
    echo
    echo "Generated by \`harness/run.sh story\`. Do not edit by hand."
    echo
    echo "| Req | Status | Result | Title |"
    echo "|-----|--------|--------|-------|"
    while IFS='|' read -r id st title; do
      files="$(req_test_files "$id")"
      key="test_r${id#R-}_"
      if [ "$st" = planned ]; then res="planned"; icon="..."
      elif [ -z "$files" ]; then res="MISSING TEST"; icon="X"; bad=$((bad + 1))
      elif echo "$results" | grep -E "^FAIL +.*${key}" >/dev/null; then res="FAIL"; icon="X"; bad=$((bad + 1))
      elif echo "$results" | grep -E "^PASS +.*${key}" >/dev/null; then res="pass"; icon="OK"
      else res="NOT RUN"; icon="X"; bad=$((bad + 1)); fi
      echo "| $id | $st | $icon $res | $title |"
    done < <(req_list)
  } > story/progress.md
  echo "story: wrote story/progress.md ($bad requirement problem(s))"
  [ "$rc" -eq 0 ] && [ "$bad" -eq 0 ]
}
