if (!window.SPELL_DATA) { (function () {
const ELEMENTS = {
  fire: '#f97316', water: '#06b6d4', earth: '#a16207', nature: '#22c55e',
  lightning: '#eab308', ice: '#38bdf8', wind: '#14b8a6', light: '#fbbf24', dark: '#6b21a8'
};

const SPELLS = [
  { id:'supernova', nameEn:'Supernova', nameVi:'Siêu Tân Tinh', recipe:['fire','fire'], category:'fire', type:'aoe', damage:850, radius:180, duration:10, cooldown:8, particleColor:['#f97316','#ef4444','#fef08a'], descEn:'Multi-stage massive explosion creating a fiery sea that lingers for 10 seconds.', descVi:'Nổ nhiều tầng, tạo biển lửa rực cháy tồn tại 10 giây.', secondaryEffectEn:'Inflicts Severe Burning for 10s', secondaryEffectVi:'Gây bỏng nặng kéo dài 10 giây' },
  { id:'steam_bomb', nameEn:'Steam Bomb', nameVi:'Bom Hơi Nước', recipe:['fire','water'], category:'fire', type:'aoe', damage:100, radius:220, duration:8, cooldown:5, particleColor:['#b45309','#78350f','#d97706','#9a3412','#f59e0b','#e2e8f0'], descEn:'A massive burst of scalding brownish-amber steam spreading over a vast radius.', descVi:'Bộc phá hơi nước nóng cuồn cuộn màu nâu trầm tỏa rộng khắp bản đồ.', secondaryEffectEn:'Scalding steam fog obscuring wide area', secondaryEffectVi:'Làn khói hơi nước nâu mù mịt diện cực rộng' },
  { id:'wildfire', nameEn:'Wildfire', nameVi:'Thảm Họa Cháy Rừng', recipe:['fire','nature'], category:'fire', type:'aoe', damage:560, radius:200, duration:8, cooldown:7, particleColor:['#16a34a','#f97316','#eab308','#dc2626'], descEn:'Grass patches sprout across the ground, instantly bursting into a roaring inferno.', descVi:'Mộc sinh Hỏa: cỏ tươi nhô lên khắp địa hình rồi bùng cháy dữ dội.', secondaryEffectEn:'Sprouts grass that ignites into clustered infernos', secondaryEffectVi:'Mọc cụm cỏ rồi bùng phát thành chuỗi bộc phá lửa' },
  { id:'magma_burst', nameEn:'Magma Burst', nameVi:'Bộc Phá Dung Nham', recipe:['fire','earth'], category:'fire', type:'aoe', damage:620, radius:140, duration:7, cooldown:6, particleColor:['#dc2626','#78350f','#f97316'], descEn:'Melts earth into molten magma, slowing enemies and burning them to ashes.', descVi:'Đất nóng chảy thành dung nham làm chậm và thiêu rụi quái vật.', secondaryEffectEn:'Creates slow magma pool', secondaryEffectVi:'Tạo vùng dung nham làm chậm 60%' },
  { id:'fire_tornado', nameEn:'Fire Tornado', nameVi:'Vòi Rồng Lửa', recipe:['fire','wind'], category:'fire', type:'vortex', damage:700, radius:150, duration:5, cooldown:8, particleColor:['#f97316','#2dd4bf','#fca5a5'], descEn:'Flaming vortex pulling enemies toward its center while immolating them.', descVi:'Lốc xoáy lửa hút quái vật vào tâm rồi thiêu đốt liên tục.', secondaryEffectEn:'Vortex pull effect', secondaryEffectVi:'Hút chặt mục tiêu vào tâm lốc' },
  { id:'plasma_spear', nameEn:'Plasma Spear', nameVi:'Thương Plasma', recipe:['fire','lightning'], category:'fire', type:'beam', damage:920, radius:40, duration:1.5, cooldown:6, particleColor:['#eab308','#ec4899','#38bdf8'], descEn:'Ultra-high voltage plasma ray piercing multiple lined-up targets instantly.', descVi:'Tia plasma siêu cao áp xuyên qua hàng loạt mục tiêu.', secondaryEffectEn:'Armor piercing beam', secondaryEffectVi:'Xuyên giáp 100% mục tiêu trên đường đi' },
  { id:'hellfire', nameEn:'Hellfire', nameVi:'Lửa Địa Ngục', recipe:['fire','dark'], category:'fire', type:'projectile', damage:880, radius:90, duration:4, cooldown:7, particleColor:['#a855f7','#18181b','#f97316'], descEn:'Dark arcane flames bypassing all elemental resistance of monsters.', descVi:'Lửa đen ma thuật bỏ qua mọi kháng phép của quái vật.', secondaryEffectEn:'Bypasses magic defense', secondaryEffectVi:'Bỏ qua 100% kháng ma thuật' },
  { id:'solar_flare', nameEn:'Solar Flare', nameVi:'Bão Nhật Hoa', recipe:['fire','light'], category:'fire', type:'aoe', damage:500, radius:220, duration:4, cooldown:9, particleColor:['#fef08a','#f97316','#ffffff'], descEn:'Blinding coronal flare causing temporary blindness and stun.', descVi:'Bão nhật hoa chói mắt, gây mờ và choáng quái vật trong vài giây.', secondaryEffectEn:'Blinds & Stuns for 3.5s', secondaryEffectVi:'Gây mù & Choáng 3.5 giây' },
  { id:'thermal_shock', nameEn:'Thermal Shock', nameVi:'Sốc Nhiệt Bộc Phá', recipe:['fire','ice'], category:'fire', type:'aoe', damage:980, radius:130, duration:2, cooldown:8, particleColor:['#38bdf8','#f97316','#ffffff'], descEn:'Instantly freezes targets then erupts in violent explosion from thermal flux.', descVi:'Đóng băng mục tiêu tức thì rồi phát nổ dữ dội do sốc nhiệt.', secondaryEffectEn:'Shatter Bonus Crit Damage', secondaryEffectVi:'Gây Sát Thương Chí Mạng Băng Vỡ' },

  { id:'tsunami', nameEn:'Tsunami', nameVi:'Sóng Thần', recipe:['water','water'], category:'water', type:'aoe', damage:480, radius:240, duration:3, cooldown:7, particleColor:['#06b6d4','#0284c7','#e0f2fe'], descEn:'Gigantic wave sweeping away projectiles and knocking back monster hordes.', descVi:'Sóng thần khổng lồ quét sạch đạn và đẩy lùi quái vật.', secondaryEffectEn:'Massive knockback + projectile reflect', secondaryEffectVi:'Đẩy lùi cực mạnh & dọn sạch đạn địch' },
  { id:'whirlpool', nameEn:'Whirlpool', nameVi:'Xoáy Nước Vực Sâu', recipe:['water','wind'], category:'water', type:'vortex', damage:520, radius:170, duration:6, cooldown:7, particleColor:['#06b6d4','#14b8a6','#0891b2'], descEn:'Swirling water vortex pulling all surrounding enemies into its center.', descVi:'Xoáy nước xoay tròn hút tất cả kẻ địch vào tâm điểm.', secondaryEffectEn:'Continuous suction + Wet status', secondaryEffectVi:'Lực hút xoáy liên tục & Ẩm ướt' },
  { id:'living_vines', nameEn:'Living Vines', nameVi:'Dây Leo Sinh Mệnh', recipe:['water','nature'], category:'water', type:'summon', damage:380, radius:130, duration:5, cooldown:6, particleColor:['#10b981','#06b6d4','#047857'], descEn:'Giant magical vines growing rapidly to bind and immobilize targets.', descVi:'Dây leo khổng lồ mọc cực nhanh trói chặt mục tiêu tại chỗ.', secondaryEffectEn:'Root / Immobilize for 5s', secondaryEffectVi:'Trói chân hoàn toàn trong 5 giây' },
  { id:'mud_prison', nameEn:'Mud Prison', nameVi:'Đầm Lầy Giam Cầm', recipe:['water','earth'], category:'water', type:'aoe', damage:350, radius:150, duration:7, cooldown:6, particleColor:['#b45309','#0891b2','#78350f'], descEn:'Thick mire erupting underneath, severely slowing and trapping enemies.', descVi:'Đầm lầy bùng phát làm chậm mạnh và giam cầm quái vật.', secondaryEffectEn:'80% Movement Slow', secondaryEffectVi:'Làm chậm di chuyển 80%' },
  { id:'thunder_pool', nameEn:'Thunder Pool', nameVi:'Vùng Nước Tích Điện', recipe:['water','lightning'], category:'water', type:'aoe', damage:750, radius:180, duration:5, cooldown:6, particleColor:['#eab308','#06b6d4','#fef08a'], descEn:'Electrically charged pool conducting chain lightning across the surface.', descVi:'Vùng nước tích điện truyền sét lan truyền diện rộng.', secondaryEffectEn:'Chain lightning propagation', secondaryEffectVi:'Truyền dòng điện giật liên hoàn' },
  { id:'abyss_water', nameEn:'Abyss Water', nameVi:'Thủy Vực U Tối', recipe:['water','dark'], category:'water', type:'beam', damage:640, radius:80, duration:4, cooldown:7, particleColor:['#a855f7','#0e7490','#3b0764'], descEn:'Deep abyss torrent draining target magic power and inflicting weakness.', descVi:'Luồng nước vực sâu hút sạch ma lực và làm suy yếu quái vật.', secondaryEffectEn:'Mana drain & attack reduction', secondaryEffectVi:'Hút 50% ma lực & giảm 40% sát thương địch' },
  { id:'rainbow_mist', nameEn:'Rainbow Mist', nameVi:'Sương Cầu Vồng', recipe:['water','light'], category:'water', type:'buff', damage:0, radius:160, duration:8, cooldown:10, particleColor:['#f472b6','#38bdf8','#fef08a','#4ade80'], descEn:'Enchanted iridescent mist continuously regenerating wizard life force.', descVi:'Sương cầu vồng ảo diệu liên tục hồi sinh lực cho bản thân.', secondaryEffectEn:'+120 Health Regen per sec', secondaryEffectVi:'Hồi 120 Máu / giây & xóa hiệu ứng xấu' },
  { id:'glacier_prison', nameEn:'Glacier Prison', nameVi:'Khối Băng Vĩnh Cửu', recipe:['water','ice'], category:'water', type:'summon', damage:510, radius:150, duration:6, cooldown:8, particleColor:['#38bdf8','#e0f2fe','#0284c7'], descEn:'Eternal permafrost pillar encasing all enemies in solid crystal ice.', descVi:'Khối băng vĩnh cửu đóng băng tuyệt đối toàn bộ kẻ địch.', secondaryEffectEn:'Absolute Freeze for 6s', secondaryEffectVi:'Đóng băng tuyệt đối trong 6 giây' },

  { id:'mountain_rise', nameEn:'Mountain Rise', nameVi:'Vách Đá Chặn Đạn', recipe:['earth','water'], category:'earth', type:'barrier', damage:300, radius:120, duration:8, cooldown:6, particleColor:['#78350f','#0284c7','#a16207'], descEn:'Erects massive stone barrier stopping enemy projectiles and blocking paths.', descVi:'Dựng vách đá chặn đạn và chặn đường di chuyển.', secondaryEffectEn:'Solid bulletproof wall', secondaryEffectVi:'Tạo vách đá kiên cố chặn đạn quái' },
  { id:'forest_fortress', nameEn:'Forest Fortress', nameVi:'Pháo Đài Cây Cối', recipe:['earth','nature'], category:'earth', type:'barrier', damage:200, radius:140, duration:10, cooldown:12, particleColor:['#15803d','#92400e','#fef08a'], descEn:'Dense ancient wooden citadel shielding allies and absorbing damage.', descVi:'Pháo đài cây cối phòng thủ kiên cố.', secondaryEffectEn:'+75% Armor Shield', secondaryEffectVi:'Tăng 75% giáp & giảm sát thương nhận vào' },
  { id:'magnetic_field', nameEn:'Magnetic Field', nameVi:'Từ Trường Đẩy Đạn', recipe:['earth','lightning'], category:'earth', type:'barrier', damage:410, radius:170, duration:6, cooldown:8, particleColor:['#eab308','#a16207','#38bdf8'], descEn:'Pulsing magnetic zone repelling metallic projectiles and disarming foes.', descVi:'Từ trường đẩy lùi đạn hoặc hút vũ khí.', secondaryEffectEn:'Deflects 100% projectiles', secondaryEffectVi:'Phản toàn bộ đạn hướng tới' },
  { id:'graveyard', nameEn:'Graveyard', nameVi:'Mộ Cổ U Tối', recipe:['earth','dark'], category:'earth', type:'summon', damage:690, radius:110, duration:5, cooldown:9, particleColor:['#581c87','#3f6212','#18181b'], descEn:'Drags targets into dark shadow graves, trapping them under dark soil.', descVi:'Kéo kẻ địch vào mộ cổ u tối.', secondaryEffectEn:'Buries targets & silences spells', secondaryEffectVi:'Chôn vùi kẻ địch & câm lặng kỹ năng' },
  { id:'crystal_garden', nameEn:'Crystal Garden', nameVi:'Vườn Tinh Thể', recipe:['earth','light'], category:'earth', type:'buff', damage:350, radius:130, duration:7, cooldown:9, particleColor:['#fef08a','#e0f2fe','#f472b6'], descEn:'Prismatic crystal clusters reflecting incoming damage back at attackers.', descVi:'Tinh thể ma thuật phản chiếu sát thương.', secondaryEffectEn:'Reflects 50% damage back', secondaryEffectVi:'Phản lại 50% sát thương cho kẻ tấn công' },
  { id:'sandstorm', nameEn:'Sandstorm', nameVi:'Bão Cát Mù Trời', recipe:['earth','wind'], category:'earth', type:'vortex', damage:480, radius:190, duration:6, cooldown:7, particleColor:['#ca8a04','#14b8a6','#fef08a'], descEn:'Blinding desert gale obscuring vision and dealing continuous abrasion.', descVi:'Bão cát che mắt giảm tầm nhìn kẻ địch.', secondaryEffectEn:'-60% Enemy Accuracy', secondaryEffectVi:'Giảm 60% độ chính xác của quái' },

  { id:'divine_judgement', nameEn:'Divine Judgement', nameVi:'Cột Sáng Thiên Phạt', recipe:['light','light'], category:'light_dark', type:'beam', damage:1200, radius:100, duration:2, cooldown:12, particleColor:['#fef08a','#ffffff','#f59e0b'], descEn:'Holy beam smiting down from the heavens, obliterating dark beings.', descVi:'Cột sáng thiên phạt dội từ trời xuống.', secondaryEffectEn:'Smite burst + Pure Holy status', secondaryEffectVi:'Gây sát thương Thánh tinh khiết cực đại' },
  { id:'photon_railgun', nameEn:'Photon Railgun', nameVi:'Pháo Quang Học', recipe:['light','lightning'], category:'light_dark', type:'beam', damage:1100, radius:35, duration:0.8, cooldown:8, particleColor:['#fef08a','#eab308','#ffffff'], descEn:'Instant light-speed photon ray piercing through entire battlefields.', descVi:'Pháo quang học vệt sáng tốc độ tức thì.', secondaryEffectEn:'Instantaneous hit scan', secondaryEffectVi:'Bắn trúng tức thì không có độ trễ' },
  { id:'black_hole', nameEn:'Black Hole', nameVi:'Hố Đen Nuốt Chửng', recipe:['dark','dark'], category:'light_dark', type:'vortex', damage:1400, radius:200, duration:6, cooldown:15, particleColor:['#3b0764','#18181b','#818cf8'], descEn:'Singularity swallowing all nearby projectiles, debris, and monsters.', descVi:'Hố đen nuốt chửng mọi đạn và vật thể.', secondaryEffectEn:'Absorbs all entity projectiles', secondaryEffectVi:'Hút và triệt hạ mọi loại vật thể' },
  { id:'shadow_storm', nameEn:'Shadow Storm', nameVi:'Bão Bóng Tối', recipe:['dark','wind'], category:'light_dark', type:'aoe', damage:720, radius:170, duration:5, cooldown:7, particleColor:['#6b21a8','#14b8a6','#0f172a'], descEn:'Dark tempest disorienting monsters and dealing chaotic dark damage.', descVi:'Bão bóng tối làm mất phương hướng quái vật.', secondaryEffectEn:'Turns monsters against each other', secondaryEffectVi:'Làm rối loạn tâm trí quái vật' },
  { id:'death_forest', nameEn:'Death Forest', nameVi:'Rừng Ma Quái', recipe:['dark','nature'], category:'light_dark', type:'summon', damage:650, radius:180, duration:8, cooldown:9, particleColor:['#4c1d95','#15803d','#a855f7'], descEn:'Cursed necrotic woods draining health from monsters continuously.', descVi:'Rừng ma quái liên tục rút sinh lực quái.', secondaryEffectEn:'Lifesteal 30% to Wizard', secondaryEffectVi:'Hút 30% máu gây ra trả cho Pháp Sư' },
  { id:'world_tree', nameEn:'World Tree', nameVi:'Cây Thế Giới', recipe:['nature','nature'], category:'light_dark', type:'buff', damage:0, radius:250, duration:12, cooldown:20, particleColor:['#22c55e','#fef08a','#10b981'], descEn:'Mythical Yggdrasil sprout bestowing revive blessing and full heal.', descVi:'Cây Thế Giới ban phước hồi sinh & gia cố.', secondaryEffectEn:'Full invulnerability & revive charge', secondaryEffectVi:'Bất tử tạm thời & nạp lượt hồi sinh' }
];

const CATEGORIES = [
  { id: 'fire', labelEn: 'Fire', labelVi: 'Lửa' },
  { id: 'water', labelEn: 'Water', labelVi: 'Nước' },
  { id: 'earth', labelEn: 'Earth', labelVi: 'Đất' },
  { id: 'light_dark', labelEn: 'Light & Dark', labelVi: 'Sáng & Tối' }
];


window.SPELL_DATA = { SPELLS, ELEMENTS, CATEGORIES };
})(); }
